_wandb:
    value:
        cli_version: 0.28.0
        e:
            p5u7lr4qty35dkhi6pyo6qx6mc5b3lv4:
                codePath: food_recommender/food_recommender_STRONG_FINAL.ipynb
                email: foyzullah.faiyaz@gmail.com
                executable: /opt/anaconda3/envs/food_rec/bin/python
                host: Mac.fritz.box
                os: macOS-26.5.1-arm64-arm-64bit
                program: food_recommender/food_recommender_STRONG_FINAL.ipynb
                python: CPython 3.11.14
                root: /Users/mdfoyzullah/food_recommender
                startedAt: "2026-07-01T23:11:26.825711Z"
                writerId: p5u7lr4qty35dkhi6pyo6qx6mc5b3lv4
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
                - 5
                - 11
                - 35
                - 49
                - 53
                - 75
            "2":
                - 1
                - 5
                - 11
                - 35
                - 49
                - 53
                - 75
            "3":
                - 2
                - 13
                - 16
            "4": 3.11.14
            "5": 0.28.0
            "6": 5.12.1
            "8":
                - 1
            "10":
                - 20
            "12": 0.28.0
            "13": darwin-arm64
lr_all:
    value: 0.005590626798054346
n_factors:
    value: 10
reg_all:
    value: 0.43314375138888334
